### ISSUE TITLE
Track rate at which emails are fetched to investigate why emails indexed is so much less than emails fetched

### ISSUE THREAD

**Issue by NickkTMD** [tiki/data#102]
Currently we are indexing a lot more emails than we are fetching
![image](https://user-images.githubusercontent.com/14880163/177618764-101adbef-abfb-46de-a6ad-fa74c5044a54.png)

We need to figure out why this is. Hypothesis is that people are closing the app before all emails are fetched. We need more metrics to determine cause.

Acceptance Criteria:
1. Track rate at which emails are fetched.

**Comment by ricardobrg** [comment]
We have the benchmark in #87.
