### ISSUE TITLE
Decide how we will track data fetching progress

### ISSUE THREAD

**Issue by ricardobrg** [tiki/data#111]
As a user I want to know the progress of data fetching (i.e. how many emails have been fetched, how many are left).
As a developer I need to be able to update the state of data fetching with new values.

Design a system to listen to fetch inbox and fetch messages commands and make this data available to be used in the UI.

Acceptance criteria:
1 - Description on how to implement this

**Comment by NickkTMD** [comment]
This can be implemented in screen service and screen model as a small addition. 

I'll make a FetchProgress class that stores data for a fetch, then have a map in screen model linking accounts to their fetch progresses. Command listeners will handle updating fetch progress.
