### ISSUE TITLE
Fix not being able to link google account on data test app

### ISSUE THREAD

**Issue by NickkTMD** [tiki/data#132]
As a developer, I need to be able to link my google account to the data example app in order to quickly test a variety of features. Right now I am unable to link the account - Google gives an error that the emulator browser is not secure enough, or something along those lines. This needs to be figured out and fixed.

the error:
![Image](https://user-images.githubusercontent.com/14880163/179618587-c3283080-42a5-454a-8ea4-04e4b22be251.png)

Acceptance Criteria
1. Able to link my google account to data test app and fetch all my emails through android emulator.

**Comment by ricardobrg** [comment]
Fixed the configuration files for Android in the example app #134
