### ISSUE TITLE
Show realtime user fetch information while a data fetch is occurring.

### ISSUE THREAD

**Issue by NickkTMD** [tiki/data#144]
As a user, I want a visual indication of when my data is being fetched, and the progress of the fetch. I also want an indication of any errors/stalling.

To fully implement this, we need a UI design, but in the meantime, the data should be presented to the user in plain text. This card is to get the data showing up accurately and in the right place - we'll make it pretty later.

Realtime data will be gotten via commands which give notifications of progress updates. 

Acceptance Criteria
1. When a data fetch is occurring, some visual indication is present on the screen
2. As a fetch occurs, progress information is displayed on the screen.
3. When an error occurs, some visual indication is present.

**Comment by ricardobrg** [comment]
blocked by #147

**Comment by NickkTMD** [comment]
Data is now accurate and updating in real time (batches of 100). Formatting is disgusting ofc.
![Image](https://user-images.githubusercontent.com/14880163/182246698-4cfa443d-ccbb-41f7-8693-144f488811f2.png)
