### ISSUE TITLE
Define account status implementation

### ISSUE THREAD

**Issue by ricardobrg** [tiki/data#147]
As a user I want to know the status of each connected account: if it is running, the progress, and if there are any errors.

Define how the account status will be implemented.
- status (running/paused/error)
- persistence (historical data)
- retrieve (real-time data)
- a model that will be displayed

Acceptance criteria
1 - Description of the implementation of account status
2 - Create new issues to implement this

**Comment by NickkTMD** [comment]
As a user, when you first scan, overall progress should be seen

Once initial scan is done and we only want to index/fetch new stuff, the user should see progress about the additional fetch only.

When fetch is done, it should say the amount fetching.

Change fetch table to:
**overall_indexed, overall_fetched, overall_total, current_indexed, current_fetched, current_total**
