### ISSUE TITLE
Allow user to add multiple accounts 

### ISSUE THREAD

**Issue by annastoilova** [tiki/data#3]
As a user, I want to add more than 1 account (gmail, or Microsoft)

desiggn ui to allow this

**Comment by ricardobrg** [comment]
The example app will implement this. It will be on hold for UI design to be implemented in TIKI app.

Acceptance criteria:
1 - Example app allowing multiple accounts.

**Comment by ricardobrg** [comment]
https://user-images.githubusercontent.com/8357343/172168285-2456701f-74b2-4938-9163-f0ef9790c58a.mov
