### ISSUE TITLE
Monitoring of the data pipeline

### ISSUE THREAD

**Issue by mike-audi** [tiki/data#71]
Using a combination of sentry and amplitude as developers should be able to determine the volume and performance of the data pipeline spanning from raw data collection all the way to the hosted knowledge graph

Acceptance Criteria:
- Data flow funnel from start to finish
- Bug/performance monitoring from start to finish

**Comment by ricardobrg** [comment]
add #73 - accounts connected

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/174710085-5124c4a5-c705-4744-b2fb-fbf016267aad.png)
