### ISSUE TITLE
Fix company domain extraction regex

### ISSUE THREAD

**Issue by ricardobrg** [tiki/data#90]
As a developer I should detect all companies domains, removing the subdomains, no matter which TLD it uses

At the moment we are not detecting correct company domains from TLDs with country specification. That leads to less data signals from companies.

Correct
sender@company.com -> company.com
sender@subdomain.company.com -> company.com

Wrong
sender@company.com.br -> .com.br 
sender@company.com.br -> .com.br 
sender@subdomains.company.com.uk -> .com.uk
sender@subdomains.company.com.uk -> .com.uk

Acceptance criteria
1 - Unit test with correct extraction

**Comment by ricardobrg** [comment]
Check if it should be done in the strategies for google and microsoft.

**Comment by NickkTMD** [comment]
![Image](https://user-images.githubusercontent.com/14880163/178039544-db3ee551-3273-452d-8d8c-fcdbfeb629c6.png)

**Comment by NickkTMD** [comment]
![Image](https://user-images.githubusercontent.com/14880163/178042427-e4560b72-9e40-456e-b47f-90755252c75f.png)

Big Picture gets the right result regardless of the amount of periods in company name.

i.e. for an email from disneyplus@mail.disneyplus.com, sending big picture mail.disneyplus.com works. Same with something longer and random like 'thiscanbeanything.multiple.apple.com.br' as shown in pic.
